site_name: My Docs
site_url: https://ricardoryn.github.io/hello_world/
theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss # 允许用户关闭顶部公告栏
extra:
  version:
    provider: mike
    alias: true
nav:
  - 主页: index.md
  - 更新日志: changelog.md
